### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by aleqx** [samzx/mphwatch#1]
You didn't post any instructions so I tried myself. I'm using nodejs 9.5.0, and did a `npm install` then tried a `nodejs app.sj` but got errors as shown below. Also tried `nodejs --experimental-modules app.js` but still no luck.

Could you post some instructions? Unless you coded this for your own use only ...

```
$ nodejs --experimental-modules app.js
(node:20489) ExperimentalWarning: The ESM module loader is experimental.
/var/www/mphstats/src/app.js:1
(function (exports, require, module, __filename, __dirname) { import React from 'react';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at createDynamicModule (internal/loader/ModuleRequest.js:52:15)
    at setExecutor (internal/loader/ModuleWrap.js:49:23)
```

**Comment by samzx** [comment]
Hi! It's currently in stealth mode and surprised it was found! I'll update the readme with instructions. But for now, you can use the following commands after `npm install`.

To view it on your local machine, `npm run-script dev-server` then visit localhost:8080 in your browser. 

If you wish to build it, you can use the command `npm run-script build`. This will dump the output files into the public folder.

If you'd like to contribute, feel free to fork and send a pull request with enhancements :)
